### ISSUE TITLE
fail build with ocaml 4.02.1

### ISSUE THREAD

**Issue by sl1pkn07** [ygrek/mldonkey#11]
Hi. with ocaml 4.02.1:

    /usr/bin/ocamlc.opt  -I src/utils/extlib  -I src/utils/cdk  -I src/utils/bitstring  -I src/utils/lib  -I src/utils/ocamlrss  -I src/utils/xml-light  -I src/utils/net  -I tools  -I src/daemon/common  -I src/daemon/driver  -I src/utils/mp3tagui  -I src/config/unix  -I src/networks/donkey -I +camlp4 -c src/utils/bitstring/bitstring_persistent.mli
    File "src/utils/bitstring/bitstring_persistent.mli", line 1:
    Error: The files /usr/lib/ocaml/pervasives.cmi
           and /usr/lib/ocaml/camlp4/Camlp4.cmi make inconsistent assumptions
       over interface Pervasives
    Makefile:5463: recipe for target 'src/utils/bitstring/bitstring_persistent.cmi' failed

greetings

**Comment by ygrek** [comment]
Looks like camlp4 was not updated with ocaml. Since ocaml 4.02 it is distributed separately.  See https://savannah.nongnu.org/bugs/index.php?43935
Probably need to add check in configure for this.

**Comment by sl1pkn07** [comment]
yep. camlp4 not update in my distro (still use 4.02.0)

then wait to distro update

thanks for the point

greetings

**Comment by sl1pkn07** [comment]
build ok. close issue

tnks again!
