### ISSUE TITLE
make "no targets" when installing on ubuntu 24.04

### ISSUE THREAD

**Issue by Andres-Chandia** [ygrek/mldonkey#114]
git clone https://github.com/ygrek/mldonkey.git
cd mldonkey
sudo apt install zlib1g-dev
sudo apt install m4
sudo apt install libgd2-dev
./configure
...........
Now execute 'gmake' to start compiling. Good luck!

make
make: *** No targets.  Stop.

gmake
gmake: *** No target was specified and no makefile was found.  Stop.

**Comment by carlonluca** [comment]
The entire output may be useful. I currently build my docker image on noble, and it seems to work fine: https://github.com/carlonluca/docker-mldonkey.

**Comment by Andres-Chandia** [comment]
Complete output....
./configure --enable-option-checking=fatal
Arguments to configure:  '--enable-option-checking=fatal'
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether the compiler supports GNU C... yes
checking whether gcc accepts -g... yes
checking for gcc option to enable C11 features... none needed
checking how to run the C preprocessor... gcc -E
checking build system type... x86_64-pc-linux-gnu
checking host system type... x86_64-pc-linux-gnu
configure: checking git revision
checking for git... yes

--------------------------------
     Checking system tools.
--------------------------------
checking for ranlib... ranlib
checking for gmake... gmake
checking for make... (cached) gmake
checking if gmake is GNU make ... yes
checking for bzip2... bzip2
checking for gzip... (cached) bzip2
checking for perl... /usr/bin/perl
checking for rpmbuild... no
checking for rpm... no
checking for wget... wget
----------------------------------------
     Checking system tools finished.
----------------------------------------

--------------------------------
     Checking OCaml compiler.
--------------------------------
checking for ocamlc.opt... /usr/bin/ocamlc.opt
checking for ocamlc... /usr/bin/ocamlc.opt
checking for camlp4... /usr/bin/camlp4
checking for ocamlopt.opt... /usr/bin/ocamlopt.opt
checking for ocamlopt... (cached) /usr/bin/ocamlopt.opt
checking for ocamldep... /usr/bin/ocamldep
checking for ocamllex.opt... /usr/bin/ocamllex.opt
checking for ocamllex... (cached) /usr/bin/ocamllex.opt
checking for ocamlyacc... /usr/bin/ocamlyacc
checking for ocamldoc... /usr/bin/ocamldoc
checking for ocamlmktop... /usr/bin/ocamlmktop
checking for camlp4... (cached) /usr/bin/camlp4
checking for camlp4of... /usr/bin/camlp4of
-------------------------------------------
     Checking OCaml 4.14.1 finished.
-------------------------------------------
checking ocaml num library... no

----------------------------------
     Checking system headers.
----------------------------------
checking for special C compiler options needed for large files... no
checking for _FILE_OFFSET_BITS value needed for large files... no
checking for stdio.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for strings.h... yes
checking for sys/stat.h... yes
checking for sys/types.h... yes
checking for unistd.h... yes
checking whether byte ordering is bigendian... no
checking for setrlimit... yes
checking for getrlimit... yes
checking for strerror_r... yes
checking for strerror... yes
checking for posix_fallocate... yes
checking for byteswap.h... yes
checking for sys/utsname.h... yes
checking for arpa/inet.h... yes
checking for sys/types.h... (cached) yes
checking for sys/time.h... yes
checking for sys/resource.h... yes
checking for netinet/in_systm.h... yes
checking for netinet/in.h... yes
checking for netinet/ip.h... yes
checking for sys/poll.h... yes
checking for poll... yes
checking for sys/vfs.h... yes
checking for sys/statvfs.h... yes
checking for sys/param.h... yes
checking for sys/mount.h... yes
-------------------------------------------
     Checking system headers finished.
-------------------------------------------

-----------------------------------
     Checking system libraries.
-----------------------------------
----- checking zlib (required)
checking for inflate in -lz... yes
checking for zlib.h... yes
checking for zlibVersion in -lz... yes
----- checking bzlib (optional)
checking for bzlib.h... yes
checking for BZ2_bzReadOpen in -lbz2... yes
checking for BZ2_bzlibVersion in -lbz2... yes
----- checking libmagic (GNU file) (optional)
checking for gcc options needed to detect all undeclared functions... none needed
checking for magic.h... no
configure: libmagic not available
----- checking gd (optional)
checking for gdlib-config... no
checking for gd.h... yes
checking for gdImageCreate in -lgd... no
configure: not found, trying another method
checking for gdImageCreate in -lgd... yes
checking for libpng-config... libpng-config
checking for png_create_read_struct  in -lpng... yes
checking for gdImagePng in -lgd... no
configure: not found, trying another method
checking for gdImagePng in -lgd... yes
checking for png support in libgd... yes
checking for png_access_version_number in -lpng... yes
checking for jpeg_CreateCompress in -ljpeg... yes
checking for gdImageJpeg in -lgd... no
configure: not found, trying another method
checking for gdImageJpeg in -lgd... yes
checking for jpeg support in libgd... yes
----- checking iconv (optional)
checking for ld used by gcc... /usr/bin/ld
checking if the linker (/usr/bin/ld) is GNU ld... yes
checking for shared library run path origin... done
checking 32-bit host C ABI... no
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for ELF binary format... yes
checking for the common suffixes of directories in the library search path... lib,lib,lib64
checking for iconv... yes
checking for working iconv... yes
checking for iconv declaration...
         extern size_t iconv (iconv_t cd, char * *inbuf, size_t *inbytesleft, char * *outbuf, size_t *outbytesleft);
checking for locale_charset... no
configure: found nl_langinfo(CODESET)
checking for locale_charset in -lcharset... no
checking for libcharset.h... no
checking for langinfo.h... yes
checking for locale.h... yes
----- checking pthread support
checking for a sed that does not truncate output... /usr/bin/sed
checking whether gcc is Clang... no
checking whether pthreads work with "-pthread" and "-lpthread"... yes
checking for joinable pthread attribute... PTHREAD_CREATE_JOINABLE
checking whether more special flags are required for pthreads... no
checking for PTHREAD_PRIO_INHERIT... yes
----- GNU C Library version
checking for linux/limits.h... yes
checking for gnu/libc-version.h... yes
checking for GNU C Library version... 2.39
---------------------------------------------
     Checking system libraries finished.
---------------------------------------------

--------------------------------------
     Checking activated networks.
--------------------------------------
checking eDonkey... yes
checking for g++... g++
checking whether the compiler supports GNU C++... yes
checking whether g++ accepts -g... yes
checking for g++ option to enable C++11 features... none needed
checking for g++... g++
checking for cryptopp/rsa.h... no
checking eDonkey SUI... no - CryptoPP library missing
checking BitTorrent... no - ocaml num library missing
checking FileTP... yes
checking Fasttrack... yes
checking DirectConnect... yes
-----------------------------------------------
     Checking activated networks finished.
-----------------------------------------------
configure: creating ./config.status
config.status: creating Makefile.config
config.status: creating mldonkey.rc
config.status: creating ../src/utils/lib/autoconf.ml.new
config.status: creating ../src/utils/lib/gAutoconf.ml.new
config.status: creating ../src/utils/bitstring/bitstring.ml
config.status: creating ../src/utils/lib/magic.ml
config.status: creating ../src/networks/donkey/donkeySui.ml
config.status: creating ../src/daemon/driver/driverGraphics.ml
config.status: creating ../packages/rpm/mldonkey.spec
config.status: creating ../packages/rpm/Makefile
config.status: creating ../packages/slackware/mldonkey.options
config.status: creating config.h
config.status: config.h is unchanged

Building dependencies (if it blocks, try 'gmake depend' to see the problem)
Building dependencies fails: try: 'gmake depend'

Configuring MLDonkey 3.2.1.git completed.
 - SCM     release-3-2-1-10-gcb0da53f
 - host    x86_64-pc-linux-gnu
 - system  linux

Network modules:
 - eDonkey           enabled (eMule SUI disabled)
 - BitTorrent                disabled - ocaml num library missing (must be installed manually when building with OCaml >= 4.06)
 - FileTP (aka wget) enabled
 - Fasttrack         enabled
 - Gnutella                  disabled - unmaintained
 - Gnutella2                 disabled - unmaintained
 - Direct Connect    enabled
 - Open Napster              disabled - currently not usable
 - Soulseek                  disabled - currently not usable
 - OpenFT                    disabled - currently not usable

Core features:
 - zlib (required)   enabled
 - bzip2             enabled
 - iconv             enabled
 - libmagic                  disabled
 - upnp & natpmp             disabled
 - graphical stats   enabled
   - png support     enabled
   - jpg support     enabled

Compilers:
 - OCaml version     4.14.1
 - gcc version       13
 - g++ version       13

Now execute 'gmake' to start compiling. Good luck!

To compile a static code execute:     gmake mlnet.static
To clean the build directory execute: gmake maintainerclean

~/mldonkey$ make
make: *** No hay objetivos.  Alto.

~/mldonkey$ gmake
gmake: *** No hay objetivos.  Alto.

Thanks!

**Comment by ygrek** [comment]
please wrap pasted output in ``` (triple backticks)
show the generated Makefile

**Comment by ygrek** [comment]
config output looks normal
Makefile didn't upload properly apparently
```
<Error>
<Code>InvalidRange</Code>
<Message>The requested range is not satisfiable</Message>
<RangeRequested>bytes=0-10485759</RangeRequested>
<ActualObjectSize>0</ActualObjectSize>
<RequestId>5ZYHW1B4PPDYECS3</RequestId>
<HostId>bKfer55IahSRxp0w91JUiErngZ2EODNq88J9ITj5cMqhk1cUx66mWs/B3WPALmiakfa6fXerYEg=</HostId>
</Error>
```
it should be small enough you can paste it directly here

**Comment by Andres-Chandia** [comment]
Thanks again for answering and sorry for taking me so long to come back...
1st. the Makefile has 5445 lines, so is not that small, at least in what concerns to lines, so I upload it again but compressed.
2nd. probably by installing dependencies and other stuff my old mldonkey installation  is running again, so I will keep that one...
[Makefile.tar.gz](https://github.com/user-attachments/files/16922397/Makefile.tar.gz)

**Comment by ygrek** [comment]
makefile looks normal, what about config/Makefile.config?

**Comment by Andres-Chandia** [comment]
Here it goes...
[MakefileConfig.tar.gz](https://github.com/user-attachments/files/16934291/MakefileConfig.tar.gz)

**Comment by ygrek** [comment]
also looks good
i re-read your original report, it says : "gmake: *** No target was specified and no makefile was found. Stop."
> no makefile was found

but you do provide Makefile
this is strange? 
do it afresh, show the output with command prompts and show output of `ls -hlA` and `find` if it fails same way

**Comment by Andres-Chandia** [comment]
Hi, thanks for all the attention you have put into this issue.
Today, my previous installation stop working so I have gone through all the process again, and it did work...
Probably recompiling with all the dependencies fulfilled made the difference, I really don't know...
But thanks again, it is working as expected...
