### ISSUE TITLE
Do not hardcode ocaml/lablgtk dependencies

### ISSUE THREAD

**Issue by anatol** [ygrek/mldonkey#14]
MLDonkey build system hardcodes dependencies to some specific versions.

Different OS' and distros have different versions and MLDonkey should not force users downgrade system compiler. Instead project should work with system compiler. For example Arch system versions are:
ocaml - 4.02.3
lablgtk2 - 2.18.3

**Comment by anatol** [comment]
Also MLDonkey carries patches for the old ocaml problem that has been fixed 5 years ago. http://caml.inria.fr/mantis/view.php?id=5237

It does not make sense to me.

**Comment by ygrek** [comment]
How it worked previously - a branch from this repo was cherry-picked into upstream cvs periodically and then release was made from cvs. And all this versioning stuff was taken care by upstream. Probably we need to modernize this, but it will be backwards incompatible (i.e. change build procedure - say switch to opam and raise minimum OCaml version - that's what I'd like to do)

**Comment by ygrek** [comment]
BTW can you provide the log when this happens, because afaics the script doesn't require hardcoded versions, but it will propose hardcoded versions if the installed one don't work (or the test is broken, see #18)
