### ISSUE TITLE
mldonkey fails to build against ocaml 4.06.0

### ISSUE THREAD

**Issue by david-geiger** [ygrek/mldonkey#25]
Hi,

We tried to compile mldonkey on Mageia Cauldron with new ocaml 4.06.0 but it fails to build, see the attached build log:

[mldonkey_build_log.txt](https://github.com/ygrek/mldonkey/files/1713376/mldonkey_build_log.txt)

Regards,
David

**Comment by ygrek** [comment]
Thanks for the report.

**Comment by david-geiger** [comment]
Thanks for the fix.
