### ISSUE TITLE
Sourceforge site empty ?

### ISSUE THREAD

**Issue by mauriziotallarico** [ygrek/mldonkey#26]
Hello,
i used to get some help/documentation from SF site but it seems empty ? 
Do you have  anew link for documentation ?
Thanks and sorry for the silly issue!

**Comment by ygrek** [comment]
Sorry, I don't know how sourceforge site is maintained, hopefully it is only a temporary glitch.
You probably should ask on http://mldonkey.sourceforge.net/forums/

**Comment by mauriziotallarico** [comment]
Thanks! In the mean time i've solved (had a minor issue on file_completed_cmd).
The forum is working but IMHO You should at least check what happened because you reference directly the SF site on the front page of the GIT project page and it's pointing to a complete useless page as of today.
