### ISSUE TITLE
Release windows binaries

### ISSUE THREAD

**Issue by DJPlaya** [ygrek/mldonkey#33]
Pretty simple, 'ip.discoveryip.com/ip.asp' is down
Using Version 3.1.3 on Win

**Comment by ygrek** [comment]
Please upgrade to newer version, it uses another service which works

**Comment by DJPlaya** [comment]
3.1.3 is the latest Version for Win as far as i can see. Or did the support for Windows got dropped?

**Comment by ygrek** [comment]
I see. Support was not dropped, just nobody is building windows binary for release. I'll try to see to that..

**Comment by DJPlaya** [comment]
Since there are still no Windows Builds, i did switched to Debian as Win 10 Subsystem. I do recommend everyone else with Windows 10 todo the same, the Gui probably dosent work, the Webinterface still does so
