### ISSUE TITLE
configure: error: unrecognized option: -cc

### ISSUE THREAD

**Issue by Arthur111** [ygrek/mldonkey#40]
Since the last commit i get this error on ./configure after git pull on MacOs.

**Comment by ygrek** [comment]
please include full output of configure

**Comment by Arthur111** [comment]
git pull
./configure

.
.
.
.
.
********  OCaml (and camlp4) version >= 4.02.3 required  *********
*******  Check http://ocaml.org/  ********
Do you want this script to try to download and install ocaml 4.08.0
LOCALLY in mldonkey directory ?
yes

.
.
.
.

x ocaml-4.08.0/BOOTSTRAP.adoc
Configuring ...
configure: error: unrecognized option: `-cc'
Try `./configure --help' for more information
cp: Makefile: No such file or directory
sed: Makefile.old: No such file or directory
Compiling ...
Makefile:20: Makefile.config: No such file or directory
Makefile:21: Makefile.common: No such file or directory
make: *** No rule to make target `Makefile.common'.  Stop.
Installing ...
Makefile:20: Makefile.config: No such file or directory
Makefile:21: Makefile.common: No such file or directory
make: *** No rule to make target `Makefile.common'.  Stop.
ln: mldonkey/patches/local/lib/ocaml/threads: No such file or directory
OCaml locally installed for mldonkey
OCaml installation failed

**Comment by DJPlaya** [comment]
Having the same Problem.
It worked for me some Months ago. now it dosent anymore, must have something todo with recent Changes.
Running on Debian Subsystem on Win10.

**Comment by ygrek** [comment]
current git version is broken with self-compiled ocaml, last commit that should work is https://github.com/ygrek/mldonkey/commit/297ee9a6344f9c5fefaab8b33a34d7a2b500f955

**Comment by ygrek** [comment]
can you test with latest git master?

**Comment by Arthur111** [comment]
git pull;make distclean;./configure;make and its ok

Its fixed
