### ISSUE TITLE
Bittorrent table of statistics is empty

### ISSUE THREAD

**Issue by ed29** [ygrek/mldonkey#42]
Hi:
I am using the bittorent network,but the bittorrnet table of statistics seems always empty.

**Comment by ygrek** [comment]
It works for me, need more info.
Please show what `stats` command actually shows.
And full output of `sysinfo` too

**Comment by ed29** [comment]
@ygrek hi,sorry for the delay of reply.Here is the info that you mentioned.

![图片](https://user-images.githubusercontent.com/3096827/73659032-603d6680-46d0-11ea-92dd-146cb9c63599.png)

![Screenshot_20200203_220010](https://user-images.githubusercontent.com/3096827/73659233-c924de80-46d0-11ea-8dc1-9654460915a1.png)
![Screenshot_20200203_220119](https://user-images.githubusercontent.com/3096827/73659234-c9bd7500-46d0-11ea-94d3-3a3a7c6be001.png)

**Comment by ygrek** [comment]
how are you sure that bittorent network is used? Is there anything suspicious (any errors?) in logs?

**Comment by ed29** [comment]
@ygrek Hi:

I think it may dued to my miss configure of mldonkey,or firewall,i can't connect to bittorrent too.So,i think it is a miss report,and close it now.

Regards,

Ed
