### ISSUE TITLE
Same IP makes many connects to the tracker buildin

### ISSUE THREAD

**Issue by ed29** [ygrek/mldonkey#43]
Hi:

There are many connects of same ip estableshed to the tracker buildin.I print the netstat and export to the file below.

For an example,ip 49.205.40.85 make 262 connects to the tracker.

[netstat-report.txt](https://github.com/ygrek/mldonkey/files/4164720/netstat-report.txt)

**Comment by ed29** [comment]
![image](https://user-images.githubusercontent.com/3096827/74154852-6a221500-4c4e-11ea-8d14-fe5e746d83d9.png)
The count of connects (mainly to tracker)

**Comment by ygrek** [comment]
I don't see why is this mldonkey problem? It depends what that other ip is doing, e.g. I can imagine it is a NAT gateway and all those connections are actually different clients, or it can be even one client with many torrents tracking on this instance and doing many simultaneous connections.

**Comment by ed29** [comment]
Ok

**Comment by ed29** [comment]
@ygrek  Hi,the mldonkey stoped,the log file:http://files.ed29.com/mlnet.log

`2020/03/16 20:06:02 [Ip] async_ip : unexpected exn socket failed: Too many open files
2020/03/16 20:06:02 Exception (socket failed: Too many open files) before connect to host 192.184.90.232:6881
2020/03/16 20:06:02 [Ip] async_ip : unexpected exn socket failed: Too many open files
2020/03/16 20:06:02 Exception (socket failed: Too many open files) before connect to host 192.184.90.232:6881
2020/03/16 20:06:02 [Ip] async_ip : unexpected exn socket failed: Too many open files
2020/03/16 20:06:02 Exception (socket failed: Too many open files) before connect to host 192.184.90.232:6881
2020/03/16 20:06:02 [Ip] async_ip : unexpected exn socket failed: Too many open files
2020/03/16 20:06:02 Exception (socket failed: Too many open files) before connect to host 192.184.90.232:6881
2020/03/16 20:06:02 [Ip] async_ip : unexpected exn socket failed: Too many open files
2020/03/16 20:06:02 [Gettext] save_strings: Error Sys_error("mlnet_strings.zh_CN.UTF-8: Too many open files")
`

**Comment by ed29** [comment]
![图片](https://user-images.githubusercontent.com/3096827/76817286-5bc2ac80-683d-11ea-9c04-86bfbe05581d.png)

**Comment by ed29** [comment]
@ygrek  Hi,sorry for that,i think it's caused by my configure of the default tracker.I filled in the default tracker in hostname style before. Now,i clear it,just leave empty,the connecting looks ok.
