### ISSUE TITLE
build: best effort to locate ocaml num library doesn't work for me

### ISSUE THREAD

**Issue by maniega** [ygrek/mldonkey#47]
Hello,

I'm getting this error while building it from a container.

To clean the build directory execute: make maintainerclean
/usr/bin/ocamlc.opt -unsafe-string -w +a-3-4-6-27-29-32-35-37-41-44-45-48-60   -I src/utils/extlib  -I src/utils/cdk  -I src/utils/bitstring  -I src/utils/lib  -I src/utils/ocamlrss  -I src/utils/xml-light  -I src/utils/net  -I tools  -I src/daemon/common  -I src/daemon/driver  -I src/utils/mp3tagui  -I src/config/unix  -I src/networks/fasttrack  -I src/networks/fileTP  -I src/networks/donkey -I +camlp4 no -c tools/ocamlpp.ml
don't know what to do with no

I think this commit is not working as expected
https://github.com/ygrek/mldonkey/commit/19d49dd73c8b926daa3156f9ba10c0638fccb486

I'm building this from a debian:testing-slim with this packages
 apt-get install -y --no-install-recommends --auto-remove --no-install-suggests zlib1g-dev ocaml ocaml-base-nox unzip autoconf wget m4 make camlp4
    ./configure --disable-bittorrent && \
    make
    mv /opt/mldonkey-master/mlnet /usr/local/bin/mlnet && \

**Comment by ygrek** [comment]
Need more details. What is ocaml version? On debian buster ocaml is 4.05 so num should be included. Please also show full configure output.

**Comment by ygrek** [comment]
I see debian:testing. Then you should install `libnum-ocaml-dev`. But configure should have failed with error.. please show full output still.

**Comment by maniega** [comment]
Thank you very much

Ocaml is 4.08, but it is working fine with libnum-ocaml-dev, I've never needed it before.

In any case, you can find the output attached

[configure.txt](https://github.com/ygrek/mldonkey/files/4857298/configure.txt)

**Comment by ygrek** [comment]
> I've never needed it before.

this is described in release notes :)
Thanks for the configure output

**Comment by maniega** [comment]
I don't want to keep you any longer, but according to release notes:
  "NB When building with OCaml >= 4.06 and Bittorrent network enabled - ocaml num library has to be present"
I'm running configure with --disable-bittorrent, and ocaml version is 4.08, i thought it complied with the requisites, i might be missing something,

I worked flawles with the library, so it is no important.

Thank you

**Comment by ygrek** [comment]
Yes, you are right, it is clear from configure output.
So this is legit bug, will keep this issue open until fixed,
