### ISSUE TITLE
Support camlp5

### ISSUE THREAD

**Issue by lgbaldoni** [ygrek/mldonkey#67]
As you may know, camlp4 was dropped by some linux distributions (namely openSUSE Tumbleweed): I've tried tinkering with it, but since I have absolutely no idea what this thing is or does, predictably I failed.

**Comment by HinTak** [comment]
Why open a new issue when an old one is already there? https://github.com/ygrek/mldonkey/issues/36 ... You haven't added anything new, such as offering a port...
