### ISSUE TITLE
ocaml 4.01 on glibc 2.34 compatibility

### ISSUE THREAD

**Issue by HinTak** [ygrek/mldonkey#69]
Upstream issue about build current ocaml on glibc 2.34 (fedora 35) system:
https://github.com/ocaml/ocaml/issues/10250

Upstream fix:
https://github.com/ocaml/ocaml/pull/10266

The patch does not apply to the older ocaml, but can be adapted. I have a working patch, but would like somebody else have a go at it...

**Comment by ygrek** [comment]
I would prefer to focus on making newer ocaml versions work, rather than spend time supporting older version :]

**Comment by HinTak** [comment]
Fair enough - I'll try to tidy it up and post it here, for those who needs something that works now...

**Comment by ygrek** [comment]
closing this
