### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by assidence** [ygrek/mldonkey#76]
Hello, I compile a static build release on ubuntu18 with kernel4.15 and glibc2.27.
I upload it to my vps which running alma8.5 with kernel4.18 and glibc2.28.
It startup failed with:
'''
2022/03/03 02:47:21 [cO] Starting MLDonkey 3.1.7 ...
2022/03/03 02:47:21 [cO] Language EN, locale UTF-8, ulimit for open files 1024
2022/03/03 02:47:21 [cO] raised ulimit for open files from 1024 to 262144
2022/03/03 02:47:21 [cO] MLDonkey is working in /home/emule/.mldonkey

2022/03/03 02:47:21 [cO] creating new MLDonkey base directory in /home/emule/.mldonkey

2022/03/03 02:47:21 [Gettext] Loading language resource mlnet_strings.en_US.UTF-8
2022/03/03 02:47:21 [cO] loaded language resource file
2022/03/03 02:47:21 [DNS] Resolving [lpa-3dedb0839a] ...
Segmentation fault (core dumped)
'''
Is that a bug or im doing something wrong please?

I have tried to located the core dump file. There is nothing.

**Comment by assidence** [comment]
https://gist.github.com/assidence/3f7c7bb6bfeca51250684938708737b0

Thanks, this is the logs.

**Comment by ygrek** [comment]
I believe this is the same as #115 , there is investigation going on there
