### ISSUE TITLE
doesn't check for ocamlopt and over 1,000 error lines

### ISSUE THREAD

**Issue by dchmelik** [ygrek/mldonkey#78]
You need to check for /ust/bin/ocamlopt also.
        After I linked ocaml.opt to that and run make, I get over 1,000 error lines but when I 'make>~/mldonkey_make_err.txt' the errors don't appear in text file--how do I redirect output so appears?

**Comment by ygrek** [comment]
>     After I linked ocaml.opt to that and run make

`ocaml.opt` is not a compiler, it is an interactive toplevel (and it is not available by default) that cannot be used instead of a compiler. If I misunderstand your report - please open new issue and show exactly what you did (with commands) and what is the output of ./configure and make.
