### ISSUE TITLE
How to start mldonkey?

### ISSUE THREAD

**Issue by marek22k** [ygrek/mldonkey#81]
Hello,

I compile 3.1.7 and get a `mlnet` file. When I start the file following appears:
```
$./mlnet 
2022/07/09 16:54:14 [cO] Starting MLDonkey 3.1.7.git ... 
2022/07/09 16:54:14 [cO] Language EN, locale UTF-8, ulimit for open files 1024
2022/07/09 16:54:14 [cO] raised ulimit for open files from 1024 to 1048576
2022/07/09 16:54:14 [cO] MLDonkey is working in /home/bandura/.mldonkey

2022/07/09 16:54:14 [cO] creating new MLDonkey base directory in /home/bandura/.mldonkey

2022/07/09 16:54:14 [Gettext] Loading language resource mlnet_strings.en_US.UTF-8
2022/07/09 16:54:14 [cO] loaded language resource file
2022/07/09 16:54:14 [DNS] Resolving [banduras-tux] ...
2022/07/09 16:54:14 [DNS] Resolving [mldonkey.sf.net] ...
2022/07/09 16:54:14 [cO] Logging in /home/bandura/.mldonkey/mlnet.log
```
Than the program exits. How can I start mldonkey without immediately exit?

**Comment by lulol** [comment]
After the line:

`2022/07/09 16:54:14 [cO] Logging in /home/bandura/.mldonkey/mlnet.log`

There should be another one showing `[dMain] Core started`

Did you try looking at the file `/home/bandura/.mldonkey/mlnet.log` to check if there is any clue about why it exits? That file is where the core redirects any further output.

I assume that you are aware that `mlnet` runs just the core, then you need to connect to it (i.e. using a gui or web browser)
