### ISSUE TITLE
MLDonkey and Ubuntu LTS 22.04 ? 

### ISSUE THREAD

**Issue by malvinas2** [ygrek/mldonkey#88]
Well, not really an issue, but is the donkey still running on Ubuntu 22.04 ? 
A simple `sudo apt-get install mldonkey-server` doesn't work. 
Can I just download the latest deb-file `mldonkey-server_3.1.7-2_amd64.deb` and do `dpkg -i mldonkey*.deb` ?

**Comment by malvinas2** [comment]
Installation of the package with dpkg seems to work, only drawback: 
As soon as I try to change the sharefolders the program crashes resp. the web interface freezes. According to the log mldonkey complains about missing read/write-permissions, but all folders (program folder, share folders etc.) belong to group mldonkey with the user mldonkey, furthermore attributes of shared folders are set to rwx for root, all groups, all users. 
So what does he complain about? 
(until a solution I use the default share folders)

**Comment by edelkas** [comment]
It doesn't seem like MLDonkey is packaged for Ubuntu 22.04 yet. Compiling from source failed for me, however, I can confirm that installing the precompiled .deb packages works. One may find plenty of working precompiled packages, of different versions and for different platforms, here, for instance:

https://debian.oregonstate.edu/debian/pool/main/m/mldonkey/
https://debian-repo.stanford.edu/debian/pool/main/m/mldonkey/

If anyone is having trouble changing the shared directories, as expressed by the OP, bear in mind that you can change these manually by editing the `downloads.ini` file. I imported (copied over) all config files from my prior installation in Ubuntu 18.04 and the migration went flawlessly.

**Comment by ygrek** [comment]
@edelkas thanks for the explanation, if you feel like submitting PR for the README about this - please do
