### ISSUE TITLE
Problem building

### ISSUE THREAD

**Issue by glechapelain** [ygrek/mldonkey#97]
Hello,

1st, I have a very strange problem merely _configuring_ mldonkey.
I 
- cloned the repository
- ran `./configure --prefix=/usr/pkg`'
When invited to download ocaml-4.01 I selected yes,
It attempted to download, but reportedly from the site at `255.255.255.255` :| (From the logs.)
There was a file where expected but it was empty (I.e. 0 Bytes.)

So I downloaded the file manually and placed it where it was expected.
The second configure around was successful.

Upon running `gmake`
The compilation died on:

File "src/utils/cdk/zlib.mli", line 20, characters 3-8:
Error: Unbound type constructor bytes
gmake: *** [Makefile:5419: src/utils/cdk/zlib.cmi] Error 2

**Comment by ygrek** [comment]
this should be fixed in latest master but note that downloading and building ocaml automatically is no longer supported, you will need to provide a working ocaml environment (opam switch) to build mldonkey
